### ISSUE TITLE
Add export to JSON function in the app

### ISSUE THREAD

**Issue by lidox** [Freshdachs/Reaction-Times#2]

**Comment by lidox** [comment]
Currently we can export a JSON file per user. for example:
{  
   "medicalId":"fjfjf",
   "operations":[  
      {  
         "medicaments":[  
            {  

            }
         ],
         "games":[  
            {  
               "game1":[  
                  {  
                     "gametype":"go-game",
                     "testtype":"pre-operation",
                     "average":"0.7951428571428573"
                  }
               ],
               "game2":[  
                  {  
                     "gametype":"go-game",
                     "testtype":"in-operation",
                     "average":"1.747"
                  }
               ],
               "game3":[  
                  {  
                     "gametype":"go-game",
                     "testtype":"post-operation",
                     "average":"0.0"
                  }
               ]
            }
         ]
      }
   ]
}

**Comment by Freshdachs** [comment]
Proposal for data structure:

`{name:"marcus", gender: "male", age: 24, games:[
	{
		datetime: "28.9.2016 11:49",
		times: [290,300,312,299],
		type: "pre"
	},
	{
		datetime: "28.9.2016 12:05",
		times: [290,300,312,299],
		type: "in"
	},
]}`

This should allow us to derive all necessary data and captures all relevant measured data.

**Comment by lidox** [comment]
Ok we got current data:
https://raw.githubusercontent.com/Freshdachs/Reaction-Times/master/data.json
